# NumPy 한번에 제대로 배우기

### NumPy 특징
##### ● Numerical Python의 약자
##### ● 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
##### ● 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
##### ● 정교한 브로드캐스팅(broadcasting) 기능
##### ● 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
##### ● 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
##### ● 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [2]:
import numpy as np
np.__version__

'1.19.2'

## 배열생성

#### 리스트로 배열 만들기

In [4]:
#1차원
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0],a1[1],a1[2],a1[3],a1[4])
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


In [5]:
#2차원
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)
print(type(a2))
print(a2.shape)
print(a2[0,0],a2[1,1],a2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)
1 5 9


In [6]:
#3차원
a3 = np.array([ [ [1,2,3],[4,5,6],[7,8,9] ],
               [ [1,2,3],[4,5,6],[7,8,9] ],
               [ [1,2,3],[4,5,6],[7,8,9] ] ])
print(a3)
print(type(a3))
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>
(3, 3, 3)


#### 배열 생성 및 초기화

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
#full은 어떤 값으로 채워야 하는지를 입력해야 한다.
np.full((3,3),1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

In [10]:
#단위행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
#삼각행렬
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [12]:
#empty는 초기화를 하지 않아서 빠르다. 
#만약 값이 들어있다면 무작위로 어딘가 배열의 주소를 참조하여 값을 보여준다.
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
print(a1)
np.zeros_like(a1)

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [14]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
print(a3)
np.full_like(a3,10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

#### 생성한 값으로 배열 생성

In [16]:
#정수 범위로 배열 생성
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [17]:
# 범위 내에서 균등 간격의 배열 생성
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
# 범위 내에서 균등 간격으로 로그 스케일로 배열 생성
np.logspace(0.1,1,20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

#### 랜덤값으로 배열 생성

In [19]:
np.random.random((3,3))

array([[0.2628001 , 0.73214242, 0.74108789],
       [0.82429343, 0.1070705 , 0.09393312],
       [0.20918565, 0.76451217, 0.48224977]])

In [20]:
np.random.randint(0,10,(3,3))

array([[2, 4, 3],
       [2, 8, 6],
       [1, 4, 5]])

In [21]:
# 정규분포를 고려한 랜덤한 수의 배열 생성
np.random.normal(0,1,(3,3))

array([[-0.42283172,  0.99120522, -1.09288941],
       [ 0.63491081, -0.45341372, -0.7921761 ],
       [ 2.5781144 , -1.36980308, -0.94165445]])

In [22]:
# 균등분포를 고려한 랜덤한 수의 배열 생성
np.random.rand(3,3)

array([[0.08332079, 0.24436056, 0.48918138],
       [0.03568785, 0.23653661, 0.36430927],
       [0.6516042 , 0.31395272, 0.85098982]])

In [23]:
# 표준 정규분포를 고려한 랜덤한 수의 배열 생성
np.random.randn(3,3)

array([[-2.01823536, -1.12480828, -0.81704587],
       [-0.15639242, -0.57064055, -0.31256047],
       [ 0.5605349 , -0.32445691,  1.25872714]])

#### 표준 데이터 타입

In [24]:
np.zeros(20,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [26]:
np.full((3,3),1.0,dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 날짜/시간 배열 생성

In [27]:
date = np.array('2020-01-01',dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [28]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [29]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [30]:
datetime = np.datetime64('2020-06-01 12:00:12.34','ns')
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')

## 배열 조회

#### 배열 속성 정보

In [31]:
def array_info(array):
    print(array)
    print("ndim:",array.ndim) #차원
    print("shape:",array.shape)
    print("dtype:",array.dtype)
    print("size:",array.size)
    print("itemsize:",array.itemsize) #한개당 크기를 의미(byte)
    print("nbytes:",array.nbytes) #전체크기(byte)
    print("strides:",array.strides) #다음차원으로 넘어가기 위한 크기

In [32]:
array_info(a1)

[4 5 6 4 5]
ndim: 1
shape: (5,)
dtype: int32
size: 5
itemsize: 4
nbytes: 20
strides: (4,)


In [33]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int32
size: 9
itemsize: 4
nbytes: 36
strides: (12, 4)


In [34]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (3, 3, 3)
dtype: int32
size: 27
itemsize: 4
nbytes: 108
strides: (36, 12, 4)


#### 인덱싱(Indexing)

In [35]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 5 6 4 5]
4
6
5
4


In [36]:
print(a2)
print(a2[0,0])
print(a2[0,2])
print(a2[-1,1])
print(a2[2,-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
8
9


In [37]:
print(a3)
print(a3[0,0,0])
print(a3[1,1,1])
print(a3[2,2,2])
print(a3[2,-1,-1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
9


#### 슬라이싱(Slicing)
##### 슬라이싱 구문: a[start:stop:step]
##### 기본값: start=0, stop=ndim, step=1

In [41]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 5 6 4 5]
[4 5]
[4 5 6 4 5]
[4]
[4 6 5]
[5 4 6 5 4]


In [42]:
print(a2)
print(a2[1])
print(a2[1,:])
print(a2[:2,:2])
print(a2[1:,::-1])
print(a2[::-1,::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


#### 불리언 인덱싱(Boolean Indexing)
##### 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
##### True 값인 인덱스의 값만 조회

In [43]:
print(a1)
bi = [False,True,True,False,True]
print(a1[bi])
bi = [True,False,True,True,True]
print(a1[bi])

[4 5 6 4 5]
[5 6 5]
[4 6 4 5]


In [44]:
print(a2)
bi = np.random.randint(0,2,(3,3),dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False  True False]
 [False False False]
 [False  True  True]]
[2 8 9]


#### 팬시 인덱싱(Fancy Indedxing)

In [45]:
print(a1)
print(a1[0],a1[2])
ind = [0,2]
print(a1[ind])
ind = np.array([ [0,1],
                 [2,0] ])
print(a1[ind])

[4 5 6 4 5]
4 6
[4 6]
[[4 5]
 [6 4]]


In [46]:
print(a2)
row = np.array([0,2])
col = np.array([1,2])
print(a2[row,col])
print(a2[row,:])
print(a2[:,col])
print(a2[row,1])
print(a2[2,col])
print(a2[row,1:])
print(a2[1:,col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]


## 배열 값 삽입/수정/삭제/복사

#### 배열 값 삽입
##### insert(): 배열의 특정 위치에 값 삽입
##### axis를 지정하지 않으면 1차원 배열로 변환
##### 추가할 방향을 axis로 지정
##### 원본 배열 변경없이 새로운 배열 반환

In [47]:
print(a1)
b1 = np.insert(a1,0,10)
print(b1)
c1 = np.insert(a1,2,10)
print(c1)

[4 5 6 4 5]
[10  4  5  6  4  5]
[ 4  5 10  6  4  5]


In [48]:
print(a2)
b2 = np.insert(a2,1,10,axis=0)
print(b2)
c2 = np.insert(a2,1,10,axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


#### 배열 값 수정
##### 배열의 인덱싱으로 접근하여 값 수정

In [49]:
print(a1)
a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)
a1[:1] = 9
print(a1)
i = np.array([1,3,4])
a1[i] = 0
print(a1)
a1[i] += 4
print(a1)

[4 5 6 4 5]
[1 2 3 4 5]
[9 2 3 4 5]
[9 0 3 0 0]
[9 4 3 4 4]


In [50]:
print(a2)
a2[0] = 1
a2[1,1] = 2
a2[2,2] = 3
print(a2)
a2[1:,2] = 9
print(a2)
row = np.array([0,1])
col = np.array([1,2])
a2[row,col] = 0
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [4 2 6]
 [7 8 3]]
[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 0 1]
 [4 2 0]
 [7 8 9]]


#### 배열 값 삭제
##### delete(): 배열의 특정 위치에 값 삭제
##### axis를 지정하지 않으면 1차원 배열로 변환
##### 삭제할 방향을 axis로 지정
##### 원본 배열 변경없이 새로운 배열 반환

In [51]:
print(a1)
b1 = np.delete(a1,1)
print(b1)

[9 4 3 4 4]
[9 3 4 4]


In [52]:
print(a2)
b2 = np.delete(a2,1,axis=0)
print(b2)
c2 = np.delete(a2,1,axis=1)
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]
[[1 1]
 [4 0]
 [7 9]]


#### 배열 복사
##### 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님
##### copy(): 배열이나 하위 배열 내의 값을 명시적으로 복사

In [53]:
print(a2)
print(a2[:2,:2])
a2_sub = a2[:2,:2]
print(a2_sub)
a2_sub[:,1] = 0
print(a2_sub)
print(a2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0]
 [4 2]]
[[1 0]
 [4 2]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]


In [54]:
print(a2)
a2_sub_copy = a2[:2,:2].copy()
print(a2_sub_copy)
a2_sub_copy[:,1] = 1
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]


## 배열 변환

#### 배열 전치 및 축 변경

In [55]:
print(a2)
print(a2.T)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [56]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [57]:
print(a2)
print(a2.swapaxes(1,0))

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [58]:
print(a3)
print(a3.swapaxes(0,1))
print(a3.swapaxes(1,2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


#### 배열 재구조화
##### reshape(): 배열의 형상을 변경
##### newaxis(): 새로운 축 추가

In [59]:
n1 = np.arange(1,10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
print(n1)
print(n1[np.newaxis,:5])
print(n1[:5,np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


#### 배열 크기 변경

In [61]:
n2 = np.random.randint(0,10,(2,5))
print(n2)
n2.resize((5,2))
print(n2)

[[0 1 2 4 8]
 [6 9 9 6 9]]
[[0 1]
 [2 4]
 [8 6]
 [9 9]
 [6 9]]


In [62]:
n2.resize((5,5))
print(n2)

[[0 1 2 4 8]
 [6 9 9 6 9]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [63]:
n2.resize((3,3))
print(n2)

[[0 1 2]
 [4 8 6]
 [9 9 6]]


#### 배열 추가
##### append(): 배열의 끝에 값 추가
##### axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [64]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.arange(10,19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [65]:
c2 = np.append(a2,b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [66]:
# axis를 0으로 지정
# shape[0]을 제외한 나머지 shape은 같아야 함
c2 = np.append(a2,b2,axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [67]:
# axis를 1로 지정
# shape[1]을 제외한 나머지 shape은 같아야 함
c2 = np.append(a2,b2,axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


#### 배열 연결
##### concatenate(): 튜플이나 배열의 리스트를 인수로 사용해 배열 연결
##### vstack(): 수직 스택(vertical stack), 1차원으로 연결
##### hstack(): 수평 스택(horizontal stack), 2차원으로 연결
##### dstack(): 깊이 스택(depth stack), 3차원으로 연결
##### stack(): 새로운 차원으로 연결

In [74]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1,b1])

array([1, 3, 5, 2, 4, 6])

In [75]:
c1 = np.array([7,8,9])
np.concatenate([a1,b1,c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [76]:
a2 = np.array([[1,2,3],[4,5,6]])
np.concatenate([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [77]:
a2 = np.array([[1,2,3],[4,5,6]])
np.concatenate([a2,a2],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [78]:
np.vstack([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [79]:
np.hstack([a2,a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [80]:
np.dstack([a2,a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

In [81]:
np.stack([a2,a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

#### 배열 분할
##### split(): 배열 분할
##### vsplit(): 수직 분할, 1차원으로 분할
##### hsplit(): 수평 분할, 2차원으로 분할
##### hsplit(): 수평 분할, 2차원으로 분할

In [82]:
a1 = np.arange(0,10)
print(a1)
b1,c1 = np.split(a1,[5])
print(b1,c1)
b1,c1,d1,e1,f1 = np.split(a1,[2,4,6,8])
print(b1,c1,d1,e1,f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


In [83]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.vsplit(a2,[2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


In [84]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.hsplit(a2,[2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


In [85]:
a3 = np.arange(1,28).reshape(3,3,3)
print(a3)
b3,c3 = np.hsplit(a3,[2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]

 [[19 20 21]
  [22 23 24]]]
[[[ 7  8  9]]

 [[16 17 18]]

 [[25 26 27]]]


## 배열 연산
##### NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
##### 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
##### 배열 요소에 대한 반복적인 계산을 효율적으로 수행

#### 브로드캐스팅(Broadcasting)

In [86]:
a1 = np.array([1,2,3])
print(a1 + 5)

a2 = np.arange(1,10).reshape(3,3)
print(a1 + a2)

b2 = np.array([1,2,3]).reshape(3,1)
print(a1 + b2)

[6 7 8]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


#### 산술 연산(Arithmetic Operators)

In [87]:
a1 = np.arange(1,10)
print(a1)
print(np.add(a1,10)) # +
print(np.subtract(a1,10)) # -
print(np.negative(a1)) # 음수
print(np.multiply(a1, 2)) # x
print(np.divide(a1,2)) # 나누기
print(np.floor_divide(a1,2)) # 나누고 내림연산
print(np.power(a1,2)) # 지수연산
print(np.mod(a1,2)) # 나머지연산

[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]


In [88]:
a1 = np.arange(1,10)
print(a1)
b1 = np.random.randint(1,10,size=9)
print(b1)
print(a1 + b1)
print(a1 - b1)
print(a1 * b1)
print(a1 / b1)
print(a1 // b1) # 나누고 내림연산
print(a1 ** b1)
print(a1 % b1)

[1 2 3 4 5 6 7 8 9]
[8 1 4 7 3 6 1 3 3]
[ 9  3  7 11  8 12  8 11 12]
[-7  1 -1 -3  2  0  6  5  6]
[ 8  2 12 28 15 36  7 24 27]
[0.125      2.         0.75       0.57142857 1.66666667 1.
 7.         2.66666667 3.        ]
[0 2 0 0 1 1 7 2 3]
[    1     2    81 16384   125 46656     7   512   729]
[1 0 3 4 2 0 0 2 0]


In [89]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.random.randint(1,10,size=(3,3))
print(b2)
print(a2 + b2)
print(a2 - b2)
print(a2 * b2)
print(a2 / b2)
print(a2 // b2) # 나누고 내림연산
print(a2 ** b2)
print(a2 % b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 3 1]
 [3 6 1]
 [6 3 6]]
[[ 5  5  4]
 [ 7 11  7]
 [13 11 15]]
[[-3 -1  2]
 [ 1 -1  5]
 [ 1  5  3]]
[[ 4  6  3]
 [12 30  6]
 [42 24 54]]
[[0.25       0.66666667 3.        ]
 [1.33333333 0.83333333 6.        ]
 [1.16666667 2.66666667 1.5       ]]
[[0 0 3]
 [1 0 6]
 [1 2 1]]
[[     1      8      3]
 [    64  15625      6]
 [117649    512 531441]]
[[1 2 0]
 [1 5 0]
 [1 2 3]]


#### 절대값 함수(Absolute Function)
##### absolute(), abs(): 내장된 절대값 함수

In [90]:
a1 = np.random.randint(-10,10,size=5)
print(a1)
print(np.absolute(a1)) # 절대값
print(np.abs(a1)) # 절대값

[  7 -10   2   4   6]
[ 7 10  2  4  6]
[ 7 10  2  4  6]


#### 제곱/제곱근 함수
##### square, sqrt: 제곱, 제곱근 함수

In [91]:
print(a1)
print(np.square(a1)) # 제곱
print(np.sqrt(a1)) # 루트

[  7 -10   2   4   6]
[ 49 100   4  16  36]
[2.64575131        nan 1.41421356 2.         2.44948974]


<ipython-input-91-c0a258d73dc8>:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(a1)) # 루트


#### 지수와 로그 함수 (Exponential and Log Function)

In [92]:
a1 = np.random.randint(1,10,size=5)
print(a1)
print(np.exp(a1)) # 지수
print(np.exp2(a1))
print(np.power(a1,2)) # 지수

[5 8 5 7 7]
[ 148.4131591  2980.95798704  148.4131591  1096.63315843 1096.63315843]
[ 32. 256.  32. 128. 128.]
[25 64 25 49 49]


In [93]:
print(a1)
print(np.log(a1)) # 로그
print(np.log2(a1))
print(np.log10(a1))

[5 8 5 7 7]
[1.60943791 2.07944154 1.60943791 1.94591015 1.94591015]
[2.32192809 3.         2.32192809 2.80735492 2.80735492]
[0.69897    0.90308999 0.69897    0.84509804 0.84509804]


#### 삼각 함수(Trigonometrical Function)

In [94]:
t = np.linspace(0,np.pi,3)
print(t)
print(np.sin(t)) # 삼각함수
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [95]:
x = [-1, 0, 1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


#### 집계 함수(Aggregate Functions)

In [96]:
a2 = np.random.randint(1,10,size=(3,3))
print(a2)
print(a2.sum(), np.sum(a2)) # 합
print(a2.sum(axis=0), np.sum(a2, axis=0))
print(a2.sum(axis=1), np.sum(a2, axis=1))

[[4 6 7]
 [9 9 6]
 [5 7 9]]
62 62
[18 22 22] [18 22 22]
[17 24 21] [17 24 21]


In [97]:
print(a2)
print(np.cumsum(a2)) # 누적합
print(np.cumsum(a2, axis=0))
print(np.cumsum(a2, axis=1))

[[4 6 7]
 [9 9 6]
 [5 7 9]]
[ 4 10 17 26 35 41 46 53 62]
[[ 4  6  7]
 [13 15 13]
 [18 22 22]]
[[ 4 10 17]
 [ 9 18 24]
 [ 5 12 21]]


In [98]:
print(a2)
print(np.diff(a2)) # 차분
print(np.diff(a2, axis=0))
print(np.diff(a2, axis=1))

[[4 6 7]
 [9 9 6]
 [5 7 9]]
[[ 2  1]
 [ 0 -3]
 [ 2  2]]
[[ 5  3 -1]
 [-4 -2  3]]
[[ 2  1]
 [ 0 -3]
 [ 2  2]]


In [99]:
print(a2)
print(np.prod(a2)) # 곱
print(np.prod(a2, axis=0))
print(np.prod(a2, axis=1))

[[4 6 7]
 [9 9 6]
 [5 7 9]]
25719120
[180 378 378]
[168 486 315]


In [100]:
print(a2)
print(np.cumprod(a2)) # 누적곱
print(np.cumprod(a2, axis=0))
print(np.cumprod(a2, axis=1))

[[4 6 7]
 [9 9 6]
 [5 7 9]]
[       4       24      168     1512    13608    81648   408240  2857680
 25719120]
[[  4   6   7]
 [ 36  54  42]
 [180 378 378]]
[[  4  24 168]
 [  9  81 486]
 [  5  35 315]]


In [101]:
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2,b2)) # 점곱
print(np.matmul(a2,b2)) # 행렬곱

[[4 6 7]
 [9 9 6]
 [5 7 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[17 17 17]
 [24 24 24]
 [21 21 21]]
[[17 17 17]
 [24 24 24]
 [21 21 21]]


In [102]:
print(a2)
print(b2)
print(np.tensordot(a2,b2)) # 텐서곱
print(np.tensordot(a2,b2,axes=0)) 
print(np.tensordot(a2,b2,axes=1)) #axes가 1이면 점곱과 같으

[[4 6 7]
 [9 9 6]
 [5 7 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
62
[[[[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]]


 [[[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]]


 [[[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]]]
[[17 17 17]
 [24 24 24]
 [21 21 21]]


In [103]:
x = [1,2,3]
y = [4,5,6]
print(np.cross(x,y)) # 백터곱

[-3  6 -3]


In [104]:
print(a2)
print(b2)
print(np.inner(a2,b2))
print(np.outer(a2,b2))

[[4 6 7]
 [9 9 6]
 [5 7 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[17 17 17]
 [24 24 24]
 [21 21 21]]
[[4 4 4 4 4 4 4 4 4]
 [6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7]
 [9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]
 [6 6 6 6 6 6 6 6 6]
 [5 5 5 5 5 5 5 5 5]
 [7 7 7 7 7 7 7 7 7]
 [9 9 9 9 9 9 9 9 9]]


In [105]:
print(a2)
print(np.mean(a2))
print(np.mean(a2, axis=0))
print(np.mean(a2, axis=1))

[[4 6 7]
 [9 9 6]
 [5 7 9]]
6.888888888888889
[6.         7.33333333 7.33333333]
[5.66666667 8.         7.        ]


In [106]:
print(a2)
print(np.std(a2))
print(np.std(a2, axis=0))
print(np.std(a2, axis=1))

[[4 6 7]
 [9 9 6]
 [5 7 9]]
1.7284832429004495
[2.1602469  1.24721913 1.24721913]
[1.24721913 1.41421356 1.63299316]


In [107]:
print(a2)
print(np.var(a2))
print(np.var(a2, axis=0))
print(np.var(a2, axis=1))

[[4 6 7]
 [9 9 6]
 [5 7 9]]
2.9876543209876543
[4.66666667 1.55555556 1.55555556]
[1.55555556 2.         2.66666667]


In [108]:
print(a2)
print(np.min(a2))
print(np.min(a2, axis=0))
print(np.min(a2, axis=1))

[[4 6 7]
 [9 9 6]
 [5 7 9]]
4
[4 6 6]
[4 6 5]


In [109]:
print(a2)
print(np.max(a2))
print(np.max(a2, axis=0))
print(np.max(a2, axis=1))

[[4 6 7]
 [9 9 6]
 [5 7 9]]
9
[9 9 9]
[7 9 9]


In [110]:
print(a2)
print(np.argmin(a2)) # 위치값이 출력
print(np.argmin(a2, axis=0))
print(np.argmin(a2, axis=1))

[[4 6 7]
 [9 9 6]
 [5 7 9]]
0
[0 0 1]
[0 2 0]


In [111]:
print(a2)
print(np.argmax(a2)) # 위치값이 출력
print(np.argmax(a2, axis=0))
print(np.argmax(a2, axis=1))

[[4 6 7]
 [9 9 6]
 [5 7 9]]
3
[1 1 2]
[2 0 2]


In [112]:
print(a2)
print(np.median(a2))
print(np.median(a2, axis=0))
print(np.median(a2, axis=1))

[[4 6 7]
 [9 9 6]
 [5 7 9]]
7.0
[5. 7. 7.]
[6. 9. 7.]


In [114]:
# percentile(): 백분위 수
a1 = np.array([0,1,2,3])
print(a1)
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='linear'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='higher'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='lower'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='nearest'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


In [115]:
a2 = np.array([ [False,False,False],
              [True,True,True],
              [False,True,True] ])
print(a2)
print(np.any(a2)) # 하나라도 True면 True가 나옴
print(np.any(a2,axis=0))
print(np.any(a2,axis=1))

[[False False False]
 [ True  True  True]
 [False  True  True]]
True
[ True  True  True]
[False  True  True]


In [116]:
print(a2)
print(np.all(a2)) # 하나라도 False면 False가 나옴
print(np.all(a2,axis=0))
print(np.all(a2,axis=1))

[[False False False]
 [ True  True  True]
 [False  True  True]]
False
[False False False]
[False  True False]


#### 비교 연산(Comparison Operators)

In [117]:
a1 = np.arange(1,10)
print(a1)
print(a1 == 5)
print(a1 != 5)
print(a1 < 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[False False False False  True  True  True  True  True]


In [118]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2 > 5))
print(np.sum(a2 > 5))
print(np.sum(a2 > 5, axis=0))
print(np.sum(a2 > 5, axis=1))
print(np.any(a2 > 5))
print(np.any(a2 > 5, axis=0))
print(np.any(a2 > 5, axis=1))
print(np.all(a2 > 5))
print(np.all(a2 > 5, axis=0))
print(np.all(a2 > 5, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]
True
[ True  True  True]
[False  True  True]
False
[False False False]
[False False  True]


#### 불리언 연산자(Boolean Operators)

In [119]:
a1 = np.array([1,2,3,4,5])
b1 = np.array([1,2,3,3,4])
print(a1)
print(b1)
print(np.isclose(a1,b1))

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [120]:
a1 = np.array([np.nan,2,np.inf,4,np.NINF])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1)) # 무한대가 아닌것

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


In [121]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)

print((a2 > 5) & (a2 < 8)) # and
print(a2[(a2 > 5) & (a2 < 8)])

print((a2 > 5) | (a2 < 8)) # or
print(a2[(a2 > 5) | (a2 < 8)])

print((a2 > 5) ^ (a2 < 8)) # xor
print(a2[(a2 > 5) ^ (a2 < 8)])

print(~(a2 > 5)) # not
print(a2[~(a2 > 5)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


#### 배열 정렬

In [122]:
a1 = np.random.randint(1,10,size=10)
print(a1)
print(np.sort(a1))
print(np.argsort(a1)) # 위치값이 출력됨
print(a1.sort())

[7 5 5 8 9 1 2 3 1 4]
[1 1 2 3 4 5 5 7 8 9]
[5 8 6 7 9 1 2 0 3 4]
None


In [123]:
a2 = np.random.randint(1,10,size=(3,3))
print(a2)
print(np.sort(a2,axis=0))
print(np.sort(a2,axis=1))

[[5 2 5]
 [8 7 9]
 [6 9 2]]
[[5 2 2]
 [6 7 5]
 [8 9 9]]
[[2 5 5]
 [7 8 9]
 [2 6 9]]


#### 부분 정렬
##### partition(): 배열에서 k개의 작은 값을 반환

In [124]:
a1 = np.random.randint(1,10,size=10)
print(a1)
print(np.partition(a1,3)) # 배열에서 k개의 작은 값을 반환(정렬)

[2 3 4 3 1 1 9 5 4 1]
[1 1 1 2 3 3 4 5 4 9]


In [125]:
a2 = np.random.randint(1,10,size=(5,5))
print(a2)
print(np.partition(a2,3))
print(np.partition(a2,3,axis=0))
print(np.partition(a2,3,axis=1))

[[6 1 7 9 3]
 [6 8 7 7 8]
 [9 4 4 7 3]
 [3 9 3 1 8]
 [4 1 7 5 3]]
[[1 3 6 7 9]
 [7 6 7 8 8]
 [3 4 4 7 9]
 [1 3 3 8 9]
 [1 3 4 5 7]]
[[3 1 3 1 3]
 [4 1 4 5 3]
 [6 4 7 7 3]
 [6 8 7 7 8]
 [9 9 7 9 8]]
[[1 3 6 7 9]
 [7 6 7 8 8]
 [3 4 4 7 9]
 [1 3 3 8 9]
 [1 3 4 5 7]]


#### 배열 입출력

In [126]:
a2 = np.random.randint(1,10,size=(5,5))
print(a2)
np.save("a",a2)

[[5 6 4 9 2]
 [3 4 9 2 5]
 [1 3 3 1 2]
 [5 7 8 3 7]
 [9 2 6 8 6]]


In [127]:
b2 = np.random.randint(1,10,size=(5,5))
print(b2)
np.savez("ab",a2,b2)

[[5 1 6 6 6]
 [2 4 2 9 3]
 [3 7 1 3 5]
 [4 6 9 2 6]
 [6 1 9 2 5]]


In [128]:
ls

 C 드라이브의 볼륨: C drive
 볼륨 일련 번호: A41F-DFFB

 C:\Users\home\anaconda3\practice\강의 디렉터리

2021-10-25  오후 06:24    <DIR>          .
2021-10-25  오후 06:24    <DIR>          ..
2021-10-22  오후 10:12    <DIR>          .ipynb_checkpoints
2021-10-22  오후 10:09               630 a.csv
2021-10-25  오후 06:25               228 a.npy
2021-10-25  오후 06:25               706 ab.npz
2021-10-22  오후 10:12               248 b.csv
2021-10-25  오후 06:24            72,137 numpy.ipynb
               5개 파일              73,949 바이트
               3개 디렉터리  53,657,923,584 바이트 남음


In [129]:
npy = np.load("a.npy")
print(npy)

[[5 6 4 9 2]
 [3 4 9 2 5]
 [1 3 3 1 2]
 [5 7 8 3 7]
 [9 2 6 8 6]]


In [130]:
npz = np.load("ab.npz")
print(npz.files)
print(npz['arr_0'])
print(npz['arr_1'])

['arr_0', 'arr_1']
[[5 6 4 9 2]
 [3 4 9 2 5]
 [1 3 3 1 2]
 [5 7 8 3 7]
 [9 2 6 8 6]]
[[5 1 6 6 6]
 [2 4 2 9 3]
 [3 7 1 3 5]
 [4 6 9 2 6]
 [6 1 9 2 5]]


In [131]:
np.savetxt("a.csv",a2,delimiter=',')

In [132]:
csv = np.loadtxt("a.csv",delimiter=',')
print(csv)

[[5. 6. 4. 9. 2.]
 [3. 4. 9. 2. 5.]
 [1. 3. 3. 1. 2.]
 [5. 7. 8. 3. 7.]
 [9. 2. 6. 8. 6.]]


In [133]:
np.savetxt("b.csv",b2,delimiter=',',fmt='%.2e',header='c1,c2,c3,c4,c5')

In [134]:
csv2 = np.loadtxt("b.csv",delimiter=',')
print(csv2)

[[5. 1. 6. 6. 6.]
 [2. 4. 2. 9. 3.]
 [3. 7. 1. 3. 5.]
 [4. 6. 9. 2. 6.]
 [6. 1. 9. 2. 5.]]
