In [1]:
import tensorflow as tf

print(tf.__version__)

### 랜덤한 수 생성

In [5]:
# 3.7 랜덤한 수 얻기 (균일 분포)
rand = tf.random.uniform([1],0,1)
print(rand)

tf.Tensor([0.67223465], shape=(1,), dtype=float32)


In [8]:
# 3.8 랜덤한 수 여러 개 얻기 (균일 분포)
rand = tf.random.uniform([5],0,1)
print(rand)

tf.Tensor([0.1355803  0.5241873  0.12584603 0.28931415 0.9743134 ], shape=(5,), dtype=float32)


In [12]:
# 3.9 랜덤한 수 여러 개 얻기 (정규 분포)
# 0과 1은 평균과 분산을 의미한다.
rand = tf.random.normal([4],0,1)
print(rand)

tf.Tensor([-1.4495299   2.3402524  -1.0795041  -0.65969384], shape=(4,), dtype=float32)


### 뉴런 만들기

In [14]:
# 3.10 sigmoid 함수
import math
def sigmoid(x):
    return 1 / (1 + math.exp(-x))

In [15]:
# 3.11 뉴런의 입력과 출력 정의
x = 1
y = 0
w = tf.random.normal([1],0,1) # 가중치
output = sigmoid(x * w)
print("output", output)

# 3.12 경사 하강법을 이용한 뉴런의 학습
for i in range(1000):
    output = sigmoid(x * w)
    error = y - output
    w = w + x * 0.1 * error
    
    if i % 100 == 99:
        print(i, error, output)

In [22]:
# 3.13 x=0 일 때 y=1 을 얻는 뉴런의 학습
# bias(편향이 필요함)
x = 0
y = 1
w = tf.random.normal([1],0,1)
b = tf.random.normal([1],0,1) # bias

for i in range(1000):
    output = sigmoid(x * w + 1 * b)
    error = y - output
    w = w + x * 0.1 * error
    b = b + 1 * 0.1 * error
    if i % 100 == 99:
        print(i, error, output)

99 0.10794136306730151 0.8920586369326985
199 0.053919449631272265 0.9460805503687277
299 0.03554773235317288 0.9644522676468271
399 0.026426966747189917 0.9735730332528101
499 0.021001198857660386 0.9789988011423396
599 0.017411106912438523 0.9825888930875615
699 0.014862902023125235 0.9851370979768748
799 0.012961824552890078 0.9870381754471099
899 0.011489823732358073 0.9885101762676419
999 0.01031671468071449 0.9896832853192855


### 첫번째 신경망 네트워크 : AND

In [23]:
# 3.15 True, False 의 정수값 확인
print(int(True))
print(int(False))

1
0


In [25]:
# 3.16 첫번째 신경망 네트워크 : AND
import numpy as np
x = np.array([[1,1], [1,0], [0,1], [0,0]])
y = np.array([[1],[0],[0],[0]])
w = tf.random.normal([2],0,1)
b = tf.random.normal([1],0,1)
b_x = 1

for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = sigmoid(np.sum(x[j]*w)+b_x*b)
        error = y[j][0] - output
        w = w + x[j] * 0.1 * error
        b = b + b_x * 0.1 * error
        error_sum += error
        
    if i % 200 == 199:
        print(i, error_sum)

199 -0.10421901190347081
399 -0.06350669642816116
599 -0.04554126076986198
799 -0.03539932317913702
999 -0.028900984764928694
1199 -0.024391499918687762
1399 -0.021083661767892323
1599 -0.018556714569632465
1799 -0.016564394111079916
1999 -0.014953970793451175


In [26]:
# 3.20 AND 네트워크의 평가
for i in range(4):
    print('X:', x[i], 'Y:', y[i], 'Output:', sigmoid(np.sum(x[i]*w)+b))

X: [1 1] Y: [1] Output: 0.9650895325583627
X: [1 0] Y: [0] Output: 0.024740372613488795
X: [0 1] Y: [0] Output: 0.0248155671106023
X: [0 0] Y: [0] Output: 2.33507778503348e-05


###  두번째 신경망 네트워크 : OR

In [27]:
# 3.21 두번째 신경망 네트워크 : OR
import numpy as np
x = np.array([[1,1], [1,0], [0,1], [0,0]])
# y 정의 
y = np.array([[1],[1],[1],[0]])

w = tf.random.normal([2],0,1)
b = tf.random.normal([1],0,1)
b_x = 1

for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = sigmoid(np.sum(x[j]*w)+b_x*b)
        error = y[j][0] - output
        w = w + x[j] * 0.1 * error
        b = b + b_x * 0.1 * error
        error_sum += error
        
    if i % 200 == 199:
        print(i, error_sum)

199 -0.04865079498534877
399 -0.02565063731658733
599 -0.017295689367731945
799 -0.013000021412396784
999 -0.010394701116161406
1199 -0.008650545964217424
1399 -0.0074028229966281375
1599 -0.006466524600301872
1799 -0.005739430082502755
1999 -0.005156773498645007


In [28]:
# 3.22 OR 네트워크의 평가
for i in range(4):
    print('X:', x[i], 'Y:', y[i], 'Output:', sigmoid(np.sum(x[i]*w)+b))

X: [1 1] Y: [1] Output: 0.999997193675912
X: [1 0] Y: [1] Output: 0.9897737587507603
X: [0 1] Y: [1] Output: 0.989754154703083
X: [0 0] Y: [0] Output: 0.025567643248753755


### 세번째 신경망 네트워크 : XOR

In [29]:
# 3.23 세번째 신경망 네트워크 : XOR
import numpy as np
x = np.array([[1,1], [1,0], [0,1], [0,0]])
y = np.array([[0],[1],[1],[0]])
w = tf.random.normal([2],0,1)
b = tf.random.normal([1],0,1)
b_x = 1

for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = sigmoid(np.sum(x[j]*w)+b_x*b)
        error = y[j][0] - output
        w = w + x[j] * 0.1 * error
        b = b + b_x * 0.1 * error
        error_sum += error
        
    if i % 200 == 199:
        print(i, error_sum)

199 0.0014085740326160723
399 5.72439586169482e-05
599 2.3249159433191835e-06
799 1.0796242444488513e-07
999 1.8614210173240053e-09
1199 1.8614210173240053e-09
1399 1.8614210173240053e-09
1599 1.8614210173240053e-09
1799 1.8614210173240053e-09
1999 1.8614210173240053e-09


In [30]:
# 3.24 XOR 네트워크의 평가
for i in range(4):
    print('X:', x[i], 'Y:', y[i], 'Output:', sigmoid(np.sum(x[i]*w)+b))

X: [1 1] Y: [0] Output: 0.5128176323940516
X: [1 0] Y: [1] Output: 0.5128176314633411
X: [0 1] Y: [1] Output: 0.4999999990686774
X: [0 0] Y: [0] Output: 0.49999999813735485


In [40]:
# 3.27 tf.keras 를 이용한 XOR 네트워크 계산
import numpy as np
x = np.array([[1,1], [1,0], [0,1], [0,0]])
# y 정의 
y = np.array([[0],[1],[1],[1]])

model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=2, activation='sigmoid', input_shape=(2,)),
    tf.keras.layers.Dense(units=1, activation='sigmoid')
])

model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.3),loss='mse')

model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_8 (Dense)              (None, 2)                 6         
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [41]:
# 3.28 tf.keras 를 이용한 XOR 네트워크 학습
history = model.fit(x,y,epochs=2000,batch_size=1)

Epoch 1/2000
4/4 [==============================] - 0s 0s/step - loss: 0.2474
Epoch 2/2000
4/4 [==============================] - 0s 1ms/step - loss: 0.2269
Epoch 3/2000
4/4 [==============================] - 0s 667us/step - loss: 0.2139
Epoch 4/2000
4/4 [==============================] - 0s 667us/step - loss: 0.2037
Epoch 5/2000
4/4 [==============================] - 0s 1000us/step - loss: 0.1981
Epoch 6/2000
4/4 [==============================] - 0s 873us/step - loss: 0.1943
Epoch 7/2000
4/4 [==============================] - 0s 641us/step - loss: 0.1920
Epoch 8/2000
4/4 [==============================] - 0s 1000us/step - loss: 0.1900
Epoch 9/2000
4/4 [==============================] - 0s 862us/step - loss: 0.1885
Epoch 10/2000
4/4 [==============================] - 0s 645us/step - loss: 0.1874
Epoch 11/2000
4/4 [==============================] - 0s 667us/step - loss: 0.1865
Epoch 12/2000
4/4 [==============================] - 0s 1ms/step - loss: 0.1855
Epoch 13/2000
4/4 [===========

In [42]:
# 3.29 tf.keras 를 이용한 XOR 네트워크 평가
model.predict(x)

array([[0.03292412],
       [0.9773612 ],
       [0.9786744 ],
       [0.9990257 ]], dtype=float32)

In [43]:
# 3.30 XOR 네트워크의 가중치와 편향 확인
for weight in model.weights:
    print(weight)

<tf.Variable 'dense_8/kernel:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.9474728,  2.5023174],
       [-3.459654 ,  1.8937237]], dtype=float32)>
<tf.Variable 'dense_8/bias:0' shape=(2,) dtype=float32, numpy=array([ 4.4395237, -2.7835305], dtype=float32)>
<tf.Variable 'dense_9/kernel:0' shape=(2, 1) dtype=float32, numpy=
array([[ 7.311276],
       [-5.13659 ]], dtype=float32)>
<tf.Variable 'dense_9/bias:0' shape=(1,) dtype=float32, numpy=array([0.00590584], dtype=float32)>
